# Site Info
title: Code Holic
tagline: 'ranlog'
description: 'S/W Develop Blog'
baseurl: ""
url: https://doll6777.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0

# About/contact
author:
  name: ran
  description: S/W developer
  contact:
    linkedin:  https://www.linkedin.com/in/doll6777
    github:    https://github.com/doll6777
    facebook:  https://www.facebook.com/
    email:     mailto:doll6777@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/categories/'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    
    - { ROS2: '/blog/categories/#ros2' }
    - { C++: '/blog/categories/#c' }
    - { 딥러닝: '/blog/categories/#딥러닝' }
    - { Java: '/blog/categories/#Java' }
    - { vision: '/blog/categories/#vision' }
    - { 안드로이드: '/blog/categories/#안드로이드' }
    - { 디자인패턴: '/blog/categories/#디자인패턴' }
    - { Kotlin: '/blog/categories/#Kotlin' }
    - { 도서: '/blog/categories/#Book' }

  Tags: 
    - '/blog/tags/'

  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/hello_page.jpg
  caption: RAN BLOG 

# Pugl-In
mathjax: true
google_analytics_token: 'UA-143415308-1'
# disqus_short_name: 'snowdeer'